<?php
/**
 * Event Model - Handles event data retrieval and processing
 */
class EventModel {
    private $config;
    
    public function __construct($config) {
        $this->config = $config;
    }
    
    /**
     * Load real events from log_data.json and Python-generated events
     */
    public function loadRealEvents() {
        $events = [];
        
        // Load from log_data.json
        $file = $this->config['data_files']['log_data'];
        $data = @file_get_contents($file);
        $events = array_merge($events, json_decode($data, true) ?: []);
        
        // Load from Python-generated security events
        $pythonEvents = $this->loadPythonSecurityEvents();
        $events = array_merge($events, $pythonEvents);
        
        // Sort by timestamp (newest first) if timestamps exist
        usort($events, function($a, $b) {
            $timeA = isset($a['timestamp']) ? strtotime($a['timestamp']) : 0;
            $timeB = isset($b['timestamp']) ? strtotime($b['timestamp']) : 0;
            return $timeB <=> $timeA;
        });
        
        return $events;
    }
    
    /**
     * Load security events generated by Python SIEM script
     */
    public function loadPythonSecurityEvents() {
        $baseDir = dirname(__DIR__, 2); // Go up to SIEMproject root
        $file = $baseDir . '/captured_logs/security_events.json';
        
        if (!file_exists($file)) {
            return [];
        }
        
        $data = @file_get_contents($file);
        $events = json_decode($data, true) ?: [];
        
        // Normalize Python events to match website format
        foreach ($events as &$event) {
            if (isset($event['severity_sticker'])) {
                // Extract severity: "Critical 🔴" -> "Critical"
                preg_match('/^(\w+)/', $event['severity_sticker'], $matches);
                $event['severity'] = $matches[1] ?? 'Low';
            }
            
            // Ensure event has all required fields
            if (!isset($event['type'])) {
                $event['type'] = $this->isInternalIP($event['source'] ?? '') ? 'INTERNAL' : 'EXTERNAL';
            }
            if (!isset($event['country'])) {
                $event['country'] = 'Unknown';
            }
            $event['from_python'] = true;
        }
        
        return $events;
    }
    
    /**
     * Check if IP address is private/internal
     */
    private function isInternalIP($ip) {
        $private_patterns = [
            '/^10\./i',
            '/^172\.(1[6-9]|2[0-9]|3[01])\./i',
            '/^192\.168\./i',
            '/^127\./i',
            '/^169\.254\./i',
            '/localhost/i'
        ];
        
        foreach ($private_patterns as $pattern) {
            if (preg_match($pattern, $ip)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * Load simulated events from sim_data.json
     */
    public function loadSimulatedEvents() {
        $file = $this->config['data_files']['sim_data'];
        $data = @file_get_contents($file);
        return json_decode($data, true) ?: [];
    }
    
    /**
     * Calculate severity counts from events
     */
    public function calculateSeverityCounts($events) {
        $severity_map = $this->config['severity_map'];
        $counts = array_fill_keys(array_keys($severity_map), 0);
        
        foreach ($events as $event) {
            $sev = $event['severity'] ?? 'Low';
            if (isset($counts[$sev])) {
                $counts[$sev]++;
            }
        }
        
        return $counts;
    }
    
    /**
     * Get most common country from external events
     */
    public function getMostCommonCountry($events) {
        $external_countries = [];
        
        foreach ($events as $event) {
            if (($event['type'] ?? '') === 'EXTERNAL' && !empty($event['country'])) {
                $external_countries[] = $event['country'];
            }
        }
        
        if (empty($external_countries)) {
            return 'None Detected';
        }
        
        $country_counts = array_count_values($external_countries);
        arsort($country_counts);
        return key($country_counts);
    }
    
    /**
     * Sort events by severity
     */
    public function sortEventsBySeverity($events) {
        $severity_order = array_flip(['Critical', 'High', 'Medium', 'Low']);
        
        usort($events, function($a, $b) use ($severity_order) {
            $sevA = $severity_order[$a['severity']] ?? 99;
            $sevB = $severity_order[$b['severity']] ?? 99;
            return $sevA <=> $sevB;
        });
        
        return $events;
    }
}

