<?php
/**
 * Event Model - Handles event data retrieval and processing
 */
class EventModel {
    private $config;
    private $logsModel = null; // Will be injected for raw log lookups
    
    public function __construct($config, $logsModel = null) {
        $this->config = $config;
        $this->logsModel = $logsModel;
    }
    
    /**
     * Set the LogsModel for raw log lookups
     */
    public function setLogsModel($logsModel) {
        $this->logsModel = $logsModel;
    }
    
    /**
     * Load real events from log_data.json and Python-generated events
     */
    public function loadRealEvents($limit = null) {
        $events = [];
        
        // Load from log_data.json
        $file = $this->config['data_files']['log_data'];
        $data = @file_get_contents($file);
        $logDataEvents = json_decode($data, true) ?: [];
        
        // Attach raw logs to log_data events
        foreach ($logDataEvents as &$event) {
            if (!isset($event['raw_logs'])) {
                $event['raw_logs'] = [];
                if ($this->logsModel !== null) {
                    $sourceIp = $event['source_ip'] ?? $event['source'] ?? '';
                    $eventTime = $event['timestamp'] ?? '';
                    
                    if ($sourceIp) {
                        $relatedLogs = $this->logsModel->getLogsNearEvent($sourceIp, $eventTime, 300);
                        $rawLines = [];
                        foreach ($relatedLogs as $log) {
                            if (isset($log['raw_line']) && !empty($log['raw_line'])) {
                                $rawLines[] = $log['raw_line'];
                            }
                        }
                        $event['raw_logs'] = $rawLines;
                    }
                }
            }
        }
        
        $events = array_merge($events, $logDataEvents);
        
        // Load from Python-generated security events
        $pythonEvents = $this->loadPythonSecurityEvents();
        $events = array_merge($events, $pythonEvents);
        
        // Sort by timestamp (newest first) if timestamps exist
        usort($events, function($a, $b) {
            $timeA = isset($a['timestamp']) ? strtotime($a['timestamp']) : 0;
            $timeB = isset($b['timestamp']) ? strtotime($b['timestamp']) : 0;
            return $timeB <=> $timeA;
        });
        
        // Limit if specified
        if ($limit !== null && is_int($limit)) {
            $events = array_slice($events, 0, $limit);
        }
        
        return $events;
    }
    
    /**
     * Load security events generated by Python SIEM script
     */
    public function loadPythonSecurityEvents() {
        $baseDir = dirname(__DIR__, 2); // Go up to SIEMproject root
        $file = $baseDir . '/captured_logs/security_events.json';
        
        if (!file_exists($file)) {
            return [];
        }
        
        $data = @file_get_contents($file);
        $events = json_decode($data, true) ?: [];
        
        // Normalize Python events to match website format
        foreach ($events as &$event) {
            if (isset($event['severity_sticker'])) {
                // Extract severity: "Critical 🔴" -> "Critical"
                preg_match('/^(\w+)/', $event['severity_sticker'], $matches);
                $event['severity'] = $matches[1] ?? 'Low';
            }
            
            // Ensure event has all required fields
            if (!isset($event['type'])) {
                $event['type'] = $this->isInternalIP($event['source'] ?? '') ? 'INTERNAL' : 'EXTERNAL';
            }
            if (!isset($event['country'])) {
                $event['country'] = 'Unknown';
            }
            
            // Add source_ip for consistency (Python events use 'source')
            if (!isset($event['source_ip']) && isset($event['source'])) {
                $event['source_ip'] = $event['source'];
            }
            
            // Fetch associated raw logs if LogsModel is available
            $event['raw_logs'] = [];
            if ($this->logsModel !== null) {
                $sourceIp = $event['source'] ?? $event['source_ip'] ?? '';
                $eventTime = $event['timestamp'] ?? '';
                
                if ($sourceIp) {
                    // Get logs from within 5 minutes of event
                    $relatedLogs = $this->logsModel->getLogsNearEvent($sourceIp, $eventTime, 300);
                    
                    // Extract raw lines and format them
                    $rawLines = [];
                    foreach ($relatedLogs as $log) {
                        if (isset($log['raw_line']) && !empty($log['raw_line'])) {
                            $rawLines[] = $log['raw_line'];
                        }
                    }
                    $event['raw_logs'] = $rawLines;
                }
            }
            
            $event['from_python'] = true;
        }
        
        return $events;
    }
    
    /**
     * Check if IP address is private/internal
     */
    private function isInternalIP($ip) {
        $private_patterns = [
            '/^10\./i',
            '/^172\.(1[6-9]|2[0-9]|3[01])\./i',
            '/^192\.168\./i',
            '/^127\./i',
            '/^169\.254\./i',
            '/localhost/i'
        ];
        
        foreach ($private_patterns as $pattern) {
            if (preg_match($pattern, $ip)) {
                return true;
            }
        }
        return false;
    }
    
    /**
     * Load simulated events from sim_data.json
     */
    public function loadSimulatedEvents($limit = null) {
        $file = $this->config['data_files']['sim_data'];
        $data = @file_get_contents($file);
        $events = json_decode($data, true) ?: [];
        
        // Attach raw logs to simulated events
        foreach ($events as &$event) {
            if (!isset($event['raw_logs'])) {
                $event['raw_logs'] = [];
                if ($this->logsModel !== null) {
                    $sourceIp = $event['source_ip'] ?? $event['source'] ?? '';
                    $eventTime = $event['timestamp'] ?? '';
                    
                    if ($sourceIp) {
                        $relatedLogs = $this->logsModel->getLogsNearEvent($sourceIp, $eventTime, 300);
                        $rawLines = [];
                        foreach ($relatedLogs as $log) {
                            if (isset($log['raw_line']) && !empty($log['raw_line'])) {
                                $rawLines[] = $log['raw_line'];
                            }
                        }
                        $event['raw_logs'] = $rawLines;
                    }
                }
            }
        }
        
        // Sort by id (newest first, assuming higher id is newer)
        usort($events, function($a, $b) {
            return ($b['id'] ?? 0) <=> ($a['id'] ?? 0);
        });
        
        // Limit if specified
        if ($limit !== null && is_int($limit)) {
            $events = array_slice($events, 0, $limit);
        }
        
        return $events;
    }
    
    /**
     * Calculate severity counts from events
     */
    public function calculateSeverityCounts($events) {
        $severity_map = $this->config['severity_map'];
        $counts = array_fill_keys(array_keys($severity_map), 0);
        
        foreach ($events as $event) {
            $sev = $event['severity'] ?? 'Low';
            if (isset($counts[$sev])) {
                $counts[$sev]++;
            }
        }
        
        return $counts;
    }
    
    /**
     * Get most common country from external events
     */
    public function getMostCommonCountry($events) {
        $external_countries = [];
        
        foreach ($events as $event) {
            if (($event['type'] ?? '') === 'EXTERNAL' && !empty($event['country'])) {
                $external_countries[] = $event['country'];
            }
        }
        
        if (empty($external_countries)) {
            return 'None Detected';
        }
        
        $country_counts = array_count_values($external_countries);
        arsort($country_counts);
        return key($country_counts);
    }
    
    /**
     * Sort events by severity
     */
    public function sortEventsBySeverity($events) {
        $severity_order = array_flip(['Critical', 'High', 'Medium', 'Low']);
        
        usort($events, function($a, $b) use ($severity_order) {
            $sevA = $severity_order[$a['severity']] ?? 99;
            $sevB = $severity_order[$b['severity']] ?? 99;
            return $sevA <=> $sevB;
        });
        
        return $events;
    }
    
    /**
     * Archive old events older than specified hours
     */
    public function archiveOldEvents($hoursOld = 24) {
        $archiveDir = dirname(__DIR__, 2) . '/archives';
        if (!is_dir($archiveDir)) {
            mkdir($archiveDir, 0755, true);
        }
        
        $cutoffTime = time() - ($hoursOld * 3600);
        
        // Archive log_data.json
        $logDataFile = $this->config['data_files']['log_data'];
        if (file_exists($logDataFile)) {
            $content = @file_get_contents($logDataFile);
            $events = json_decode($content, true) ?: [];
            
            $current = [];
            $archive = [];
            
            foreach ($events as $event) {
                $eventTime = isset($event['timestamp']) ? strtotime($event['timestamp']) : 0;
                if ($eventTime < $cutoffTime) {
                    $archive[] = $event;
                } else {
                    $current[] = $event;
                }
            }
            
            if (!empty($archive)) {
                $archiveFile = $archiveDir . '/log_data_' . date('Y-m-d_H-i-s') . '.json';
                file_put_contents($archiveFile, json_encode($archive, JSON_PRETTY_PRINT));
            }
            
            file_put_contents($logDataFile, json_encode($current, JSON_PRETTY_PRINT));
        }
        
        // Archive security_events.json
        $securityFile = dirname(__DIR__, 2) . '/captured_logs/security_events.json';
        if (file_exists($securityFile)) {
            $content = @file_get_contents($securityFile);
            $events = json_decode($content, true) ?: [];
            
            $current = [];
            $archive = [];
            
            foreach ($events as $event) {
                $eventTime = isset($event['timestamp']) ? strtotime($event['timestamp']) : 0;
                if ($eventTime < $cutoffTime) {
                    $archive[] = $event;
                } else {
                    $current[] = $event;
                }
            }
            
            if (!empty($archive)) {
                $archiveFile = $archiveDir . '/security_events_' . date('Y-m-d_H-i-s') . '.json';
                file_put_contents($archiveFile, json_encode($archive, JSON_PRETTY_PRINT));
            }
            
            file_put_contents($securityFile, json_encode($current, JSON_PRETTY_PRINT));
        }
    }
}

